package testgen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// draftCase is a rule-generated test case before it is converted into a
// testmanagement.TestCase. Kept as a plain struct so the parsing logic in
// this file has zero dependency on the testmanagement package or the
// database — it is pure, deterministic, and independently testable.
type draftCase struct {
	Title          string
	Preconditions  string
	Action         string
	ExpectedResult string
	Priority       string // low | medium | high | critical
}

// field is a unified view of an OpenAPI parameter or request body property.
type field struct {
	Name     string
	Location string // query | path | header | body
	Schema   map[string]interface{}
	Required bool
}

// GenerateDraftCases walks an OpenAPI 3.0/3.1 document (already decoded into
// a generic map, e.g. from json.Unmarshal) and deterministically produces
// draft test cases: one happy path per endpoint, plus negative cases for
// every required field, enum constraint, type mismatch, string/numeric
// boundary, and auth requirement it finds. Nothing here is inferred or
// generated by a model — every case comes directly from a rule matching a
// concrete piece of the spec. Endpoints are visited in sorted path/method
// order so output is stable across runs on the same spec.
func GenerateDraftCases(spec map[string]interface{}) (cases []draftCase, endpointCount int) {
	paths, _ := spec["paths"].(map[string]interface{})
	if paths == nil {
		return nil, 0
	}

	type opKey struct {
		path   string
		method string
	}
	var keys []opKey
	pathItems := make(map[opKey]struct {
		pathItem  map[string]interface{}
		operation map[string]interface{}
	})

	for path, rawItem := range paths {
		pathItem, ok := rawItem.(map[string]interface{})
		if !ok {
			continue
		}
		for method, rawOp := range pathItem {
			m := strings.ToLower(method)
			if m != "get" && m != "post" && m != "put" && m != "patch" && m != "delete" {
				continue
			}
			operation, ok := rawOp.(map[string]interface{})
			if !ok {
				continue
			}
			key := opKey{path: path, method: m}
			keys = append(keys, key)
			pathItems[key] = struct {
				pathItem  map[string]interface{}
				operation map[string]interface{}
			}{pathItem, operation}
		}
	}

	sort.Slice(keys, func(i, j int) bool {
		if keys[i].path != keys[j].path {
			return keys[i].path < keys[j].path
		}
		return keys[i].method < keys[j].method
	})

	for _, key := range keys {
		entry := pathItems[key]
		cases = append(cases, generateForOperation(spec, key.method, key.path, entry.pathItem, entry.operation)...)
	}

	return cases, len(keys)
}

func generateForOperation(spec map[string]interface{}, method, path string, pathItem, operation map[string]interface{}) []draftCase {
	methodU := strings.ToUpper(method)
	fields := collectFields(spec, pathItem, operation)
	authNeeded := requiresAuth(spec, operation)
	var cases []draftCase

	// --- happy path ---
	var actionParts []string
	if authNeeded {
		actionParts = append(actionParts, "Authenticate with a valid API token")
	}
	byLocation := map[string]map[string]interface{}{}
	for _, f := range fields {
		if byLocation[f.Location] == nil {
			byLocation[f.Location] = map[string]interface{}{}
		}
		byLocation[f.Location][f.Name] = exampleValue(f.Schema)
	}
	var locs []string
	for loc := range byLocation {
		locs = append(locs, loc)
	}
	sort.Strings(locs)
	for _, loc := range locs {
		b, _ := json.Marshal(byLocation[loc])
		actionParts = append(actionParts, fmt.Sprintf("send %s %s with %s = %s", methodU, path, loc, string(b)))
	}
	if len(fields) == 0 {
		actionParts = append(actionParts, fmt.Sprintf("send %s %s with no parameters", methodU, path))
	}

	preconditions := "API is reachable"
	if authNeeded {
		preconditions += " and a valid auth token is available"
	}

	cases = append(cases, draftCase{
		Title:          fmt.Sprintf("%s %s — valid request succeeds", methodU, path),
		Preconditions:  preconditions,
		Action:         capitalize(strings.Join(actionParts, "; ")) + ".",
		ExpectedResult: fmt.Sprintf("Response status is %s and the body matches the documented schema.", successStatus(operation)),
		Priority:       "high",
	})

	// --- auth cases ---
	if authNeeded {
		cases = append(cases, draftCase{
			Title:          fmt.Sprintf("%s %s — missing auth token is rejected", methodU, path),
			Preconditions:  "API is reachable",
			Action:         fmt.Sprintf("Send %s %s with no Authorization header.", methodU, path),
			ExpectedResult: "Response status is 401 Unauthorized.",
			Priority:       "high",
		})
		cases = append(cases, draftCase{
			Title:          fmt.Sprintf("%s %s — invalid auth token is rejected", methodU, path),
			Preconditions:  "API is reachable",
			Action:         fmt.Sprintf("Send %s %s with an expired or malformed token.", methodU, path),
			ExpectedResult: "Response status is 401 or 403.",
			Priority:       "high",
		})
	}

	// --- per-field negative cases ---
	for _, f := range fields {
		if f.Required {
			cases = append(cases, draftCase{
				Title:          fmt.Sprintf("%s %s — missing required '%s' (%s) returns 400", methodU, path, f.Name, f.Location),
				Preconditions:  preconditions,
				Action:         fmt.Sprintf("Send %s %s omitting '%s' from the %s.", methodU, path, f.Name, f.Location),
				ExpectedResult: "Response status is 400 and the error identifies the missing field.",
				Priority:       "high",
			})
		}

		if wt, ok := wrongTypeValue(f.Schema); ok {
			b, _ := json.Marshal(wt)
			schemaType, _ := f.Schema["type"].(string)
			if schemaType == "" {
				schemaType = "string"
			}
			cases = append(cases, draftCase{
				Title:          fmt.Sprintf("%s %s — '%s' with wrong type returns 400", methodU, path, f.Name),
				Preconditions:  preconditions,
				Action:         fmt.Sprintf("Send %s %s with '%s' = %s (expected %s).", methodU, path, f.Name, string(b), schemaType),
				ExpectedResult: "Response status is 400 and the error identifies the invalid type.",
				Priority:       "medium",
			})
		}

		if enumVals, ok := f.Schema["enum"].([]interface{}); ok && len(enumVals) > 0 {
			cases = append(cases, draftCase{
				Title:          fmt.Sprintf("%s %s — '%s' with value outside its enum returns 400", methodU, path, f.Name),
				Preconditions:  preconditions,
				Action:         fmt.Sprintf("Send %s %s with '%s' = \"not-a-valid-option\" (allowed: %v).", methodU, path, f.Name, enumVals),
				ExpectedResult: "Response status is 400 and the error lists the allowed values.",
				Priority:       "medium",
			})
		}

		for _, direction := range []string{"below", "above"} {
			bad, ok := outOfRangeValue(f.Schema, direction)
			if !ok {
				continue
			}
			isString, _ := f.Schema["type"].(string)
			var bound string
			if isString == "string" {
				if direction == "below" {
					bound = "min length"
				} else {
					bound = "max length"
				}
			} else if direction == "below" {
				bound = "minimum"
			} else {
				bound = "maximum"
			}
			b, _ := json.Marshal(bad)
			cases = append(cases, draftCase{
				Title:          fmt.Sprintf("%s %s — '%s' %s %s boundary returns 400", methodU, path, f.Name, direction, bound),
				Preconditions:  preconditions,
				Action:         fmt.Sprintf("Send %s %s with '%s' = %s (%s the allowed %s).", methodU, path, f.Name, string(b), direction, bound),
				ExpectedResult: "Response status is 400 and the error identifies the out-of-range field.",
				Priority:       "medium",
			})
		}
	}

	return cases
}

func collectFields(spec map[string]interface{}, pathItem, operation map[string]interface{}) []field {
	var fields []field

	appendParams := func(raw interface{}) {
		list, _ := raw.([]interface{})
		for _, rawParam := range list {
			param, ok := rawParam.(map[string]interface{})
			if !ok {
				continue
			}
			name, _ := param["name"].(string)
			loc, _ := param["in"].(string)
			required, _ := param["required"].(bool)
			schema := resolveSchema(spec, asMap(param["schema"]))
			fields = append(fields, field{Name: name, Location: loc, Schema: schema, Required: required})
		}
	}
	appendParams(pathItem["parameters"])
	appendParams(operation["parameters"])

	if body, ok := operation["requestBody"].(map[string]interface{}); ok {
		content, _ := body["content"].(map[string]interface{})
		if appJSON, ok := content["application/json"].(map[string]interface{}); ok {
			bodySchema := resolveSchema(spec, asMap(appJSON["schema"]))
			requiredSet := map[string]bool{}
			if reqList, ok := bodySchema["required"].([]interface{}); ok {
				for _, r := range reqList {
					if s, ok := r.(string); ok {
						requiredSet[s] = true
					}
				}
			}
			if props, ok := bodySchema["properties"].(map[string]interface{}); ok {
				var names []string
				for name := range props {
					names = append(names, name)
				}
				sort.Strings(names)
				for _, name := range names {
					propSchema := resolveSchema(spec, asMap(props[name]))
					fields = append(fields, field{
						Name:     name,
						Location: "body",
						Schema:   propSchema,
						Required: requiredSet[name],
					})
				}
			}
		}
	}

	return fields
}

func requiresAuth(spec, operation map[string]interface{}) bool {
	if sec, ok := operation["security"].([]interface{}); ok {
		return len(sec) > 0
	}
	if sec, ok := spec["security"].([]interface{}); ok {
		return len(sec) > 0
	}
	return false
}

func successStatus(operation map[string]interface{}) string {
	responses, _ := operation["responses"].(map[string]interface{})
	var codes []string
	for code := range responses {
		codes = append(codes, code)
	}
	sort.Strings(codes)
	for _, code := range codes {
		if strings.HasPrefix(code, "2") {
			return code
		}
	}
	return "200"
}

func resolveSchema(spec map[string]interface{}, schema map[string]interface{}) map[string]interface{} {
	if schema == nil {
		return map[string]interface{}{}
	}
	if ref, ok := schema["$ref"].(string); ok {
		return resolveSchema(spec, resolveRef(spec, ref))
	}
	return schema
}

func resolveRef(spec map[string]interface{}, ref string) map[string]interface{} {
	if !strings.HasPrefix(ref, "#/") {
		return map[string]interface{}{}
	}
	parts := strings.Split(strings.TrimPrefix(ref, "#/"), "/")
	var node interface{} = spec
	for _, part := range parts {
		m, ok := node.(map[string]interface{})
		if !ok {
			return map[string]interface{}{}
		}
		node = m[part]
	}
	m, _ := node.(map[string]interface{})
	return m
}

func asMap(v interface{}) map[string]interface{} {
	m, _ := v.(map[string]interface{})
	return m
}

func exampleValue(schema map[string]interface{}) interface{} {
	if ex, ok := schema["example"]; ok {
		return ex
	}
	t, _ := schema["type"].(string)
	if t == "" {
		t = "string"
	}
	switch t {
	case "string":
		if enum, ok := schema["enum"].([]interface{}); ok && len(enum) > 0 {
			return enum[0]
		}
		if format, _ := schema["format"].(string); format == "date-time" {
			return "2026-08-03T00:00:00Z"
		}
		return "sample-value"
	case "integer":
		if min, ok := schema["minimum"]; ok {
			return min
		}
		return 1
	case "number":
		if min, ok := schema["minimum"]; ok {
			return min
		}
		return 1.0
	case "boolean":
		return true
	case "array":
		items := asMap(schema["items"])
		return []interface{}{exampleValue(items)}
	default:
		return nil
	}
}

func wrongTypeValue(schema map[string]interface{}) (interface{}, bool) {
	t, _ := schema["type"].(string)
	switch t {
	case "string":
		return 12345, true
	case "integer", "number":
		return "not-a-number", true
	case "boolean":
		return "not-a-boolean", true
	case "array":
		return "not-an-array", true
	case "object":
		return "not-an-object", true
	default:
		return nil, false
	}
}

func outOfRangeValue(schema map[string]interface{}, direction string) (interface{}, bool) {
	t, _ := schema["type"].(string)
	switch t {
	case "integer", "number":
		if direction == "below" {
			if min, ok := numberValue(schema["minimum"]); ok {
				return min - 1, true
			}
		} else {
			if max, ok := numberValue(schema["maximum"]); ok {
				return max + 1, true
			}
		}
	case "string":
		if direction == "below" {
			if minLen, ok := numberValue(schema["minLength"]); ok && minLen > 0 {
				return strings.Repeat("x", int(minLen)-1), true
			}
		} else {
			if maxLen, ok := numberValue(schema["maxLength"]); ok {
				return strings.Repeat("x", int(maxLen)+1), true
			}
		}
	}
	return nil, false
}

func numberValue(v interface{}) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case int:
		return float64(n), true
	default:
		return 0, false
	}
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
