export const WEB = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  mfaSetup: "/mfa-setup",
  onboarding: "/onboarding",
  createWorkspace: "/create-workspace",
  dashboard: "/dashboard",
  projects: "/dashboard/projects",
  testCases: "/dashboard/test-cases",
  newTestCase: "/dashboard/test-cases/new",
  testPlans: "/dashboard/test-plans",
  newTestPlan: "/dashboard/test-plans/new",
  testRuns: "/dashboard/test-runs",
  newTestRun: "/dashboard/test-runs/new",
  defects: "/dashboard/defects",
  automation: "/dashboard/automation",
  apiTests: "/dashboard/api-tests",
  analytics: "/dashboard/executive",
  notifications: "/dashboard/notifications",
  settings: "/dashboard/settings",
  integrations: "/dashboard/settings/integrations",
  members: "/dashboard/settings/members",
};

export const API = {
  register: "/api/v1/auth/register",
  login: "/api/v1/auth/login",
  logout: "/api/v1/auth/logout",
  refresh: "/api/v1/auth/refresh",
  me: "/api/v1/auth/me",
  csrf: "/api/v1/auth/csrf",
  passwordResetRequest: "/api/v1/auth/password-reset/request",
  passwordResetConfirm: "/api/v1/auth/password-reset/confirm",
  organizations: "/api/v1/organizations",
  workspaces: "/api/v1/workspaces",
  projects: "/api/v1/projects",
  testCases: "/api/v1/test-cases",
  testPlans: "/api/v1/test-plans",
  testRuns: "/api/v1/test-runs",
  testRunItems: "/api/v1/test-run-items",
  defects: "/api/v1/defects",
  automationProjects: "/api/v1/automation/projects",
  automationExecutions: "/api/v1/automation/executions",
  apiCollections: "/api/v1/api-collections",
  apiEnvironments: "/api/v1/api-environments",
  apiRequests: "/api/v1/api-requests",
  apiExecutions: "/api/v1/api-executions",
  notifications: "/api/v1/notifications",
  notificationPreferences: "/api/v1/notification-preferences",
  integrations: "/api/v1/integrations",
  search: "/api/v1/search",
  analyticsSummary: "/api/v1/analytics/summary",
  analyticsExport: "/api/v1/analytics/export/csv",
  health: "/health",
};
